### ISSUE TITLE
Conflict with DFred’s Convenient Effects

### ISSUE THREAD

**Issue by ctbritt** [caewok/fvtt-token-visibility#12]
With DFred’s Convenient Effects enabled, automatic cover doesn’t work because of existing conditions in Dfred’s. 

Suggestion: Check for Dfred’s enablement and use those conditions instead of inbuilt ones if on. 

Thanks!
Chris

**Comment by ctbritt** [comment]
Just saw the update! Huzzah!

**Comment by caewok** [comment]
Yep! Let me know if you find any weirdness with it; I am sure it could use additional testing.
