### ISSUE TITLE
With new version of Levels, all tokens are not visible while a token is selected

### ISSUE THREAD

**Issue by Zamrod** [caewok/fvtt-token-visibility#13]
With levels 3.5.7 any time a token is selected, you see none of the other tokens but only while Alternate Token Visibility is enabled.

**Comment by caewok** [comment]
Probably related to this change
https://github.com/theripper93/Levels/blob/d9a48ca21e353413d2d631fa03273a5a28a1dcf7/scripts/wrappers.js#L129-L174
