### ISSUE TITLE
Unexpected interaction with Force Client Settings and DF Settings Clarity

### ISSUE THREAD

**Issue by weepingminotaur** [caewok/fvtt-token-visibility#23]
When Alt Token Visibility is enabled with Force Client Settings, DF Settings Clarity, and dependent modules (libwrapper and Socketlib), changing the "lock" state of any module setting (open lock, soft-force, or closed lock) closes the Configure Game Settings page entirely (though changes are saved). I've verified on a clean world with nothing installed but the above modules. When Alt Token V is off, behavior is normal (changing the lock state doesn't close the whole dialog).

Foundry v10 build 291, PF2e 4.4.2

**Comment by caewok** [comment]
Should be resolved in v0.3.7.

**Comment by weepingminotaur** [comment]
Yes, it works fine now -- thank you!
