### ISSUE TITLE
Dfred's Cover effects being applied for each attack, not just once per attacker. 

### ISSUE THREAD

**Issue by ctbritt** [caewok/fvtt-token-visibility#26]
Hi! Thanks for incorporating Dfred's cover effects into the module. The only problem is it's getting applied for each attack. So if a player has two attacks against a target with cover, the cover is stacking for the second attack. 

As shown here for a second attack. 
![CleanShot 2022-12-07 at 12 52 28@2x](https://user-images.githubusercontent.com/4516034/206257954-de6b1410-6352-4df6-9760-db6b288c08ab.png)

**Comment by caewok** [comment]
Should be resolved in v0.3.7.
