### ISSUE TITLE
Area and Are3d cover calcs say no cover even when target blocked by another token

### ISSUE THREAD

**Issue by ctbritt** [caewok/fvtt-token-visibility#27]
Area and Area3d cover calcs don't return half cover when a target has a token between it and the attacker. (should be half cover.)

DMG algorithm works fine, but these don't. 

with DMG algorthm
<img width="689" alt="CleanShot 2022-12-07 at 12 54 50@2x" src="https://user-images.githubusercontent.com/4516034/206258847-9ad22261-b36f-478d-8243-61364240a7ca.png">

Area and Area3d algorithm
<img width="703" alt="CleanShot 2022-12-07 at 12 55 45@2x" src="https://user-images.githubusercontent.com/4516034/206259147-6b5ae63d-83f7-4a13-bdeb-26f907c3b3e6.png">

**Comment by caewok** [comment]
Do you have Wall Height module enabled? I suspect that without Wall Height enabled, it is not reading the token as having any height. Without any height, it would not consider it to have cover.

**Comment by caewok** [comment]
v0.3.8 should fix this for Area3d. The Area2d version needs more work.

**Comment by caewok** [comment]
How does this look in v0.4.0?

**Comment by ctbritt** [comment]
Yeah, I'm seeing total cover now when token are in the way, when 3D cover algorithm is on.
