### ISSUE TITLE
DFreds Convenient Effects and High/Total Cover

### ISSUE THREAD

**Issue by gurgugnao** [caewok/fvtt-token-visibility#31]
Hello again, DFreds Convenient Effects removed the possibility to set High/Total Cover. Sometimes, depending on the LoS and Cover algorithm, targets get High/Total Cover, but without setting it, it does not modify MiQol workflow or give any bonus to the targets.
Is there a possibility to set High/Total Cover even if using DFreds Convenient Effects (maybe creating an effect with this module) or to add an option on MiQol workflow (under mechanics - walls block ranged attacks) to check for High/Total Cover? Thank you!

**Comment by caewok** [comment]
I could probably re-add it.  But keep in mind that currently, the default High/Total Cover has no active effects associated with it. So even if I re-add that option, it will not provide any bonuses unless you set them. 

I would love to add some for the defaults, but I cannot figure out how to add effects that would prevent ranged attacks and ranged spell attacks but not prevent area spell effects (think, fireball). (I am ambivalent on whether melee attacks should be blocked by full cover; it just seems like a situation that will not often come up, so I could go either way.)

Of course, if you don't care about area spell effects, then simply bumping up the AC bonus to, say +99, would probably do the trick.

**Comment by gurgugnao** [comment]
Yes, I understand. The solution for now, as per the other issue I posted, it's just use "Ask GM to confirm" option and correct cover as required. Thanks!

**Comment by caewok** [comment]
Addressed in v0.4.4. You should now be able to set the default High/Total cover effect even if DFreds is active. Note that DFreds was throwing an error, but the dev accepted my PR and that should be fixed in a more recent version of DFreds.
