### ISSUE TITLE
Levels LoS overwrites ATV LoS with "Points on token" algorithm

### ISSUE THREAD

**Issue by gurgugnao** [caewok/fvtt-token-visibility#32]
I am so fond of your module that I am bothering you with a 3rd issue this morning :)

It seems  that Levels LoS overwrite ATV LoS when "Points on token" algorithm is selected. On the other hand, it works correctly (using ATV LoS algorithm) if you select Area 2D or 3D algorithm.
The problem about Levels LoS is that it uses a center-center or center-corners algorithm (enabled or disabled by selecting "Precise token visibility" option in Levels settings).

**LoS decided by Levels (corner of the token)**
- Levels activated and Precise token visibility selected
- ATV set to Points on token and Foundry default (9 points)

![Levels LoS](https://user-images.githubusercontent.com/122090327/210999211-c3730092-cd4b-43b5-95b1-307a7e57144e.jpg)

**LoS decided by ATV**
- Levels deactivated
- ATV set to Points on token and Foundry default (9 points)

![ATV LoS1](https://user-images.githubusercontent.com/122090327/210999551-68f82cc5-9cb5-478a-af23-7e9db9a3f430.jpg)
![ATV LoS2](https://user-images.githubusercontent.com/122090327/210999656-5336321e-f73b-4636-a979-b10a5e903641.jpg)

**Comment by caewok** [comment]
Can you just unselect Precise token visibility? Or does that still not work?

**Comment by gurgugnao** [comment]
Even if you just unselect Precise token visibility, it still does not work.

**Comment by caewok** [comment]
This will be fixed in v0.6.0. It will no longer defer to Levels. In addition, you can approximately replicate the Levels' `Precise token visibility` and `Exact token visibility` by using the `inset` control I am adding in v0.6.0.
