### ISSUE TITLE
Error with 0.40 update

### ISSUE THREAD

**Issue by gurgugnao** [caewok/fvtt-token-visibility#33]
Hi, after updating your module yesterday I started incurring in this error.
![Error 0 4 0](https://user-images.githubusercontent.com/122090327/211200455-17ac5242-55c9-4015-aa3c-a10eaf717e51.jpg)

**Comment by caewok** [comment]
Does v0.4.1 fix this error?

**Comment by gurgugnao** [comment]
Yes, now it works fine, thank you!

**Comment by gurgugnao** [comment]
Hello, new error with version 0.4.3
![Error](https://user-images.githubusercontent.com/122090327/223088091-c5808b2e-db4f-4797-b57b-0429c3feef3f.jpg)
