### ISSUE TITLE
Length null error

### ISSUE THREAD

**Issue by caewok** [caewok/fvtt-token-visibility#37]
Hello, new error with version 0.4.3
![Error](https://user-images.githubusercontent.com/122090327/223088091-c5808b2e-db4f-4797-b57b-0429c3feef3f.jpg)

_Originally posted by @gurgugnao in https://github.com/caewok/fvtt-token-visibility/issues/33#issuecomment-1455896562_

**Comment by caewok** [comment]
Should be addressed in v0.4.4. Please let me know if that is not the case.

**Comment by ElroTheOnk** [comment]
I can't quickly reproduce on the scene where it happened very reliably, so at the very least you've drastically reduced the frequency! Will keep an eye out, and let you know if it crops up again anywhere.

**Comment by gurgugnao** [comment]
In my scene now it works fine, thanks!
