### ISSUE TITLE
[BUG] Interaction between Alternative Token vision and Monk's Combat Details' "Show Start Token" setting: Soundwave overlay effect is applied to current combatant

### ISSUE THREAD

**Issue by MS-PBS** [caewok/fvtt-token-visibility#39]
**Describe the bug**
When in combat, if ATV is active and MCD's "Show Start Token" setting is enabled, the moving token gets the soundwave overlay effect that applies when a token is hidden.

**To Reproduce**
1. Have Alternative Token Vision and MCD (and dependencies) active. 
2. Make sure that "Show Start Token" is enabled.
3. Start a combat and move the current combatant
4. The soundwave overlay effect for hidden tokens (the one added on Foundry V10) will be applied to the current combatant.

**Expected behavior**
No overlay should be applied. It doesn't make sense to apply this effect to the token you're currently controlling.

**Screenshots**

https://user-images.githubusercontent.com/68601994/226176237-09c28bc7-0e94-4889-813d-213b41d5f30a.mp4

**Please complete as much of the following information as possible:**
 - Browser: Firefox
 - Foundry Version 10 b 291
 - System: PF2e
 - Module version: 0.4.3
 - Are there any errors in the console? -> No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction -> It is a module interaction but I'm hoping it can be solved if there's something you can do on your end. Otherwise it's at least interesting.

**Context**

I also reported this on MLD's page: https://github.com/ironmonk88/monks-combat-details/issues/20

**Comment by caewok** [comment]
Reported fixed in MLD.
