### ISSUE TITLE
Unexpected error when selecting token with vision enabled

### ISSUE THREAD

**Issue by T-Whiz** [caewok/fvtt-token-visibility#40]
Expected: Selecting a token with Vision Enabled displays the parts of the map viewable by the token, based on the token's vision settings, scene settings, and lighting.

Actual: When there are 2 or more tokens and at least 1 token has Vision Enabled checked, and the scene has at least 1 wall, an error message appears in the console and the selection tool no longer appears to select tokens until the scene is refreshed. Attached screen shots and settings, and copy of log.
Active modules: Alternative Token Visibility v0.4.4, libWrapper v1.12.12.0, The Forge v1.10
Foundry Virtual Tabletop: Version 10, 10.291
Game System: dnd5e, 2.1.5

Steps to recreate:
Prerequisites: Alternative Token Visibility settings set as in attached screen shots.
1.	Create a new scene with Token Vision enabled and Global Illumination enabled (or add one or more light sources).
2.	Add 1 or more walls.
3.	Add two or more tokens to the scene, where at least one of the tokens has Vision Enabled checked.
4.	Select a token that has vision enabled.

[screen shots.pdf](https://github.com/caewok/fvtt-token-visibility/files/11216882/screen.shots.pdf)
[log.log](https://github.com/caewok/fvtt-token-visibility/files/11216885/log.log)

**Comment by caewok** [comment]
Fixed in v0.4.5. Thanks for the detailed screen shots!
