### ISSUE TITLE
SF Cover compatibility

### ISSUE THREAD

**Issue by Iankid** [caewok/fvtt-token-visibility#43]
The SF system does not use the Effects system. Instead relying on it's own Modifiers system to effect sheet stats.
This may be fixed by adding/removing a condition item to the player's sheet with the condition's activation. As the rest of the conditions do.

**Comment by caewok** [comment]
Added in v0.5.4. Cover items should be in a compendium. I used what I thought would be reasonable condition effects, but I am not familiar with the system. If you think the default active effects should be different, or you see other issues, please feel free to open a new issue.
