### ISSUE TITLE
[Request] New Midiqol Attack Workflow Option

### ISSUE THREAD

**Issue by txm3278** [caewok/fvtt-token-visibility#45]
Currently the Midiqol Attack Workflow option has 4 options:
- Do not test for cover
- Ask user to confirm.
- Ask GM to confirm.
- Apply automatically

I would like a new option where, it will only pop up if any target has cover, it asks the user to confirm whether they want to make the attack or not, but does not allow them to edit the cover of the target.

**Comment by caewok** [comment]
Added in v0.5.4.
