### ISSUE TITLE
Wall hight dont work properly ...

### ISSUE THREAD

**Issue by R0TEAM** [caewok/fvtt-token-visibility#5]
Have an Token with TokenHight 2 (token self is at 0 hight)
Have an Token with TokenHight 3 (token self is at 0 hight)
Have an wall with hight parameter > bottom 6, high 26, that is partly between the 2 Tokens

If i calculate cover with this modul, it says "Three Quarter Cover" .... 
if i remove the wall (where was always over the tokens) it is no cover

**Comment by caewok** [comment]
Which cover algorithm are you using (in the settings)?
Are you using dnd5e?

**Comment by R0TEAM** [comment]
look at #4

**Comment by caewok** [comment]
Possibly fixed in v0.3.0. Feel free to re-open an issue if this persists.
