### ISSUE TITLE
[BUG] Check cover nonfunctional on latest version

### ISSUE THREAD

**Issue by weepingminotaur** [caewok/fvtt-token-visibility#50]
Just updated to 0.5.4. Re-imported measure cover macro. Whenever I try to measure cover, I get a console error telling me to select a token first even though I have a token selected. Happens in combat and out of combat.

**Comment by weepingminotaur** [comment]
This is Pathfinder 2e, by the way.

**Comment by caewok** [comment]
This sounds like an old version of the macro. Try updating to v0.5.5, import the macro again, and see if it works. If not, can you copy the macro script here so I can see what it is doing?

**Comment by weepingminotaur** [comment]
Updating to 0.5.5 and re-importing the macro seems to have fixed the problem. Thank you!

**Comment by caewok** [comment]
Glad to hear it!
