### ISSUE TITLE
Conflict with Midi

### ISSUE THREAD

**Issue by ctbritt** [caewok/fvtt-token-visibility#51]
Getting this error with new version of ATV: 
![CleanShot 2023-09-15 at 10 45 43](https://github.com/caewok/fvtt-token-visibility/assets/4516034/1fd2ae1e-455c-4050-99ab-568e12ad75da)

FTC tracked down to a conflict with Midi. 

Versions: 
Foundry 11.308
Dnd5e 2.3.1
ATV: 0.5.4
Midi: 11.0.18

**Comment by caewok** [comment]
Can you give me steps you are taking to make the error appear? And what cover settings are you using in Alternative Token Visibility? (I tried but cannot make that error appear using midi.)

**Comment by ctbritt** [comment]
I'm still getting this error even with just ATV, midi, libwrapper and socketlib activated.

**Comment by caewok** [comment]
I still cannot replicate this. Maybe it is something specific to the midi combat? Can you give me an example attack that makes this happen? (For example, target a token with a shortbow when it has half-cover...)

**Comment by caewok** [comment]
Also, can you send me a JSON file with your midiqol settings? (In midiqol settings, click the Workflow Settings button, go to the Misc. tab, and then click "Export midi-qol settings to json file." Send me the JSON file.) You will probably need to zip the file to upload it to Git. Alternatively, if you can open the JSON in a text editor, you can just copy/paste the contents into a Git comment.

**Comment by caewok** [comment]
Closed as not replicable.
