### ISSUE TITLE
Conflict with Visions

### ISSUE THREAD

**Issue by rinnocenti** [caewok/fvtt-token-visibility#55]
with the vision module, there is a conflict. With both modules, the tokens can no longer be seen between them.

**Comment by caewok** [comment]
What is the "vision module"? There are several modules that have "vision" in the name. And does this error occur all the time, or only under a specific condition?

**Comment by GhostwheelX** [comment]
[This one](https://github.com/dev7355608/vision-5e), if that helps.

**Comment by caewok** [comment]
I installed Vision 5e, and my tokens can still see one another. Which tells me that it is probably a specific setting that causes the error. When you select a token, and it cannot see other tokens, what features/effects does it have related to the vision categories described in the [Vision 5e git](https://github.com/dev7355608/vision-5e)? And what Line of Sight algorithm do you have selected in the Alternative Token Visibility settings?

**Comment by rinnocenti** [comment]
No, but it seems that vision fixed it, because in the latest versions the problem no longer occurs

**Comment by rinnocenti** [comment]
I will test with the new versions, as it seems that this bug has been changed. For now I will close the order and if it appears specifically I will open a new one.
