### ISSUE TITLE
Token movement is extremely choppy

### ISSUE THREAD

**Issue by Zamrod** [caewok/fvtt-token-visibility#6]
With the module enabled token movement becomes very choppy after you let go of a token. One move of a token also shows over a thousand warnings for:

```
visibility_range.js:103 Test point has los mapping already.
```

Without any other modules, it is still choppy but somewhat manageable. If you enable a couple other modules the choppiness gets much worse.

![image](https://user-images.githubusercontent.com/12570777/201447432-8161eefa-a177-4468-a151-8be55c738666.png)

**Comment by caewok** [comment]
I fixed the warnings and cached the LOS value in v 0.3.0. Hopefully less choppy now, but feel free to open a new issue with more details if this persists.
