### ISSUE TITLE
Non-vision senses have no effect when using 'Token inset corners and center (5 points)' option for Range Points and Vision 5e is enabled

### ISSUE THREAD

**Issue by T-Whiz** [caewok/fvtt-token-visibility#62]
When Vision 5e is enabled and the ATV Range Points setting is 'Token inset corners and center (5 points)', tokens lose the ability to use any non-vision senses (hearing, tremorsense, etc.). When ATV Range Points is set to any other option then senses work as expected.

Verified this occurs with only ATV and dependencies and Vision 5e enabled. No errors in console.
Foundry v11.313, dnd5e 2.1.3, ATV v0.5.8, socketlib v1.0.13, libWrapper v1.12.13.0, Vision 5e v1.10.4, hosting: The Forge

Steps to recreate:
1. In ATV, select the 'Token inset corners and center (5 points)' option for Range Points.
2. Enable the Vision 5e module (if not already enabled).
3. Add 2 Starter Heroes to the scene from the SRD Starter Heroes compendium.
4. Add the Blind condition to one of the tokens and then select the Blind token.

**Comment by caewok** [comment]
Closed as I think this is fixed in v0.6 series.
